### PR TITLE
WIP Upgrade to LibCImGui

### PR DESCRIPTION
**Pull request by wsphillips**
start generating function wrappers for cimplot v0.9

### CODE REVIEW

**Comment by sairus7** [comment]
Call me if you need something fixed outside generator code.

**Comment by wsphillips** [comment]
@sairus7 the wrappers are fixed up so that they load, but the demo is broken because it looks like CImGui has been restructured on the development branch. Since I think you've been using the latest versions can you try to update the Renderer script and see if you can get the demo running?

The generated wrappers should be very close to what we need. If something is busted ping me--it's probably just a small edit here or there that's needed. For the moment the methods from implot_internal.h are filtered out because I'll need some special casing to handle it and I want to focus on getting the main API and demo working first.

**Comment by sairus7** [comment]
How should I deal with warnings like this?
`WARNING: both ImPlot and LibCImGui export "ImPlotPoint"; uses of it in module MyImPlot must be qualified` 
For now I just add module name.

UPD: Nevermind, conflicts dissapeared after `import ImPlot: LibCImGui`

**Comment by sairus7** [comment]
Looks like every name `libcimplot` should be replace to `libcimgui` in generator. I've replaced it manually for now. Also fixed some api function names.

Demo working until Drag and Drop, except of Queries:
```no method matching unsafe_convert(::Type{Ptr{ImPlotLimits}}, ::ImPlotLimits)```

**Comment by wsphillips** [comment]
> Looks like every name `libcimplot` should be replace to `libcimgui` in generator. I've replaced it manually for now. Also fixed some api function names.

Ah yeah. It was hardcoded in the generator script. When we're sure it's all working I need to once again refactor generator.jl to remove redundant code blocks and fix things like that.

> Demo working until Drag and Drop, except of Queries:
> `no method matching unsafe_convert(::Type{Ptr{ImPlotLimits}}, ::ImPlotLimits)`

Awesome!

**Comment by sairus7** [comment]
Also, since we dropped CImGui from ImPlot env, to run examples you need to activate separate env in the demo folder, and have `dev` both ImPlot and CImGui in your system.

**Comment by wsphillips** [comment]
@sairus7 removed the submodule (and Manifest.toml for good measure). Does that fix things for you? Any reason to not just merge this to main? We can decide to tag it at a later time if needed?

**Comment by sairus7** [comment]
Yes, thanks, now I can just `add CImGui#master ImPlot#upgrade-v0.9`, and it works.

I agree we should merge this PR into main!

**Pull request merged**
