### PR TITLE
Implot update

### PR DESCRIPTION
**Pull request by JamesWrigley**
This is a rather large PR that updates the package to work with ImGui v1.89.4 and ImPlot v0.14. There's quite a few separate changes so I would recommend reviewing each commit individually.

Depends on:
- https://github.com/Gnimuc/CImGui.jl/pull/87
- https://github.com/JuliaImGui/cimgui-pack/pull/1
- https://github.com/JuliaPackaging/Yggdrasil/pull/7197

And I think it'll need a new release of Clang.jl with https://github.com/JuliaInterop/Clang.jl/pull/441.

### CODE REVIEW

**Comment by sairus7** [comment]
Nice work!

Also, there are some new demo examples in latest version that can be ported here as well: https://github.com/epezent/implot/blob/v0.14/implot_demo.cpp

And some commented out examples may have been fixed with the new version.

I don't think it's necessary to work through all of them, but it is good test cases for the new fucntionality.

**Comment by wsphillips** [comment]
Hey this is awesome--thank you for taking the time to work on it. I will review in the next couple days

**Comment by JamesWrigley** [comment]
> Nice work!
> 
> Also, there are some new demo examples in latest version that can be ported here as well: https://github.com/epezent/implot/blob/v0.14/implot_demo.cpp
> 
> And some commented out examples may have been fixed with the new version.
> 
> I don't think it's necessary to work through all of them, but it is good test cases for the new fucntionality.

That's true, I think I can port the commented out examples tomorrow but implementing more from the official examples would be a bit more work :sweat_smile: I think the soonest I could get to those is in ~3 weeks or so. BTW I updated the script with the official demo in e5e24c3, I didn't notice but it was broken before because it seems to have been written before ImGuiGLFWBackend.jl started generating its own wrappers instead of using GLFW.jl.


> Hey this is awesome--thank you for taking the time to work on it. I will review in the next couple days

Sounds good, thanks :)

**Comment by sairus7** [comment]
> BTW I updated the script with the official demo in [e5e24c3](https://github.com/wsphillips/ImPlot.jl/commit/e5e24c3be43bda278938ccb4d0469df54e0d27cd), I didn't notice but it was broken before because it seems to have been written before ImGuiGLFWBackend.jl started generating its own wrappers instead of using GLFW.jl.

It mostly duplicates [Renderer.jl](https://github.com/JamesWrigley/ImPlot.jl/blob/implot-update/demo/Renderer.jl) code, which is used in ported demo. I think we could use it across all examples. Just wrap any example code with `render` function.

**Comment by JamesWrigley** [comment]
Ah I see. Maybe I can expose that from CImGui.jl then :thinking:

**Comment by wsphillips** [comment]
Pulled all the branches and tested this--and all seems to work just fine. There's a quite a bit left to reproduce on `implot_demo.jl`  wrt getting us up to parity with the current implot demo, but the existing demo plots look to be working. @sairus7 @Gnimuc do we want to start merging all these changes? At least to the development branches of the respective repos?

**Comment by sairus7** [comment]
I dev'ed @JamesWrigley forks for ImPlot and CImGui, tried `implot_demo.jl` and got the following error:
```julia
julia> show_demo()
┌ Error: Error in renderloop!
│   exception = UndefVarError: `igCollapsingHeader_TreeNodeFlags` not defined
└ @ CImGui.Renderer C:\Users\gvg\.julia\dev\CImGui\src\renderer.jl:144
```

**Comment by JamesWrigley** [comment]
Did you dev these packages too?
- CImGuiPack_jll (this needs to be built locally, see https://github.com/Gnimuc/CImGui.jl/discussions/52#discussioncomment-6731563)
- LibCImGui.jl (this is probably the one causing problems)
- ImGuiGLFWBackend.jl

**Comment by sefffal** [comment]
I dev’d everything (easier now that the jll is merged) and the implot demo is working well!

**Comment by sairus7** [comment]
Before this is merged we should tag 0.3.0 release for the current master branch. @wsphillips what do you think?

**Comment by JamesWrigley** [comment]
(I would suggest including #28 in a v0.3 too)

**Comment by wsphillips** [comment]
Hey @sairus7 @JamesWrigley I was out of town--I will do a tag and release either today or tomorrow.

**Comment by wsphillips** [comment]
To clarify: The master branch is at v0.3.0 but has not been officially tagged to the public registry. Would you like to tag ImPlot.jl before the updates as it is now on master, THEN merge these PRs and tag a new version (e.g. 0.4.0)? Or do we want to merge all the updates and call that v0.3.0?

The former would result in two public registry versions while the later would be an all in one update from the old existing public v0.2.0.

**Comment by sairus7** [comment]
I mean one version for current master and another version after this PR merged. Now I'm using CImGui and ImPlot master branch in my projects, and I want to use the same version after transition to 1.89.4, so that ideally nothing will break.

**Comment by wsphillips** [comment]
@sairus7 Current master tagged to v0.3.0, I'm merging the PRs for the updates to master now and will tag 0.4.0

> I mean one version for current master and another version after this PR merged. Now I'm using CImGui and ImPlot master branch in my projects, and I want to use the same version after transition to 1.89.4, so that ideally nothing will break.

**Comment by sairus7** [comment]
@wsphillips I don't see any v0.3.0 or v0.4.0 tag or release now - last tag is v0.2.0 (I mean git tag and github release)

**Comment by wsphillips** [comment]
I havent tagged it (will do) but v0.3.0 is on the registry, pointing to the last commit before the PR merge... I just have not tagged via git on the repo. I have not yet tagged or versioned v0.4.0 on the registry or the repo

**Comment by wsphillips** [comment]
v0.3.0 tagged at the commit matching the registry now

**Pull request merged**
