### PR TITLE
Generator script update

### LINKED ISSUE #17: Update ImGui version?
What should be done do add a newer ImGui version as a dependency?
Should we wait for CImGui.jl 1.82.0 release, or move to LibCImGui 1.82.2 only?

### PR DESCRIPTION
**Pull request by wsphillips**
Puts us on the road for easy implot upgrades (which will fix #17 )

### CODE REVIEW

**Comment by sairus7** [comment]
I will try to check if `implot_demo` examples are working.
Are we still on 1.79 here, with no tables? Maybe we should depend on LibCImGui instead of CImGui?

**Comment by wsphillips** [comment]
I would say lets get this running first. It's going to be a moving target because using LibCImGui means we have to also update the implot bindings. It should generally _just work_ to regenerate using newer cimplot headers now, but the test will be "what happens with the internal API added" I might have to add more cases to match against or write an independent node/expression processor script for the internal API.

The first bug you will hit is some method ambiguities. Comment the offending high-level methods out for now. I am working on handling it directly in the generator by tightening some arguments and widening others so it all just works. The main thing to do is check up on how the demo runs (libcimplot bindings should be sufficient for it) and updating the sections involving pointers if and when necessary.

Since we have the pointer access methods available now, we should be able to (for instance) simplify a lot of the stuff surrounding `ImPlotStyle` handling. Overall expect to be deleting or reducing a lot of syntax :smile:

**Comment by wsphillips** [comment]
@sairus7 I have up to heatmaps working, hitting another edge case that I'll try to solve. I'll stick to making as much headway as I can with the generator script itself

**Comment by wsphillips** [comment]
@sairus7 all demos should work now, but I haven't don't any substantial revisions to improve some of the old kludges. With some cleanup to the generator script/directory I think this can get merged and we can address upgrading in a separate PR (i.e. don't fuss with the current demo too much until we start implementing the updates)

**Comment by sairus7** [comment]
NIce, looks like most of changes are made in generator.jl script? `Legend` and `Custom Data and Getters` sections are not working for me (opening them crashes Julia process). I think there are some problems in `PlotLineG`

**Comment by wsphillips** [comment]
can you confirm you've pulled the most recent changes from this branch? I can open both of those just fine locally.

**Comment by sairus7** [comment]
Yes, I see your last commit ed22cb6.
Here it crashes:
```julia
sinewave_c = @cfunction(MyImPlot.SineWave, ImPlotPoint, (Ptr{Cvoid}, Cint))
...
ImPlot.PlotLineG("Item 1", sinewave_c, data1, 1000) # <-- here it crashes
# called with types: String, Ptr{Nothing}, Base.RefValue{Main.MyImPlot.WaveData}, Int64
```
And the function itself:
```julia
function PlotLineG(label_id, getter, data, count::Integer, offset::Integer = 0)
    ccall((:ImPlot_PlotLineG, libcimplot), Cvoid, (Cstring, Ptr{Cvoid}, Ptr{Cvoid}, Cint, Cint), label_id, getter, data, count, offset)
end
```
Or maybe I should recompile something?

**Comment by sairus7** [comment]
By the way, I'm on Win10, if it helps.

**Comment by wsphillips** [comment]
> By the way, I'm on Win10, if it helps.

Yeah I'm wondering if this is some weird platform-related issue. There's nothing materially different about those wrappers and I haven't touched that part of the demo. I don't understand how that breaks if you were able to run it on the `main` branch previously :thinking:

Are you getting a segfault or is there a Julia stack trace you can share?

I will reboot to my Windows partition and see if I can reproduce in the meantime.

**Comment by sairus7** [comment]
Here is error message:
```julia
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x610cc00b -- unsafe_load at .\pointer.jl:105 [inlined]
unsafe_load at .\pointer.jl:105 [inlined]
SineWave at C:\Users\user\code\ImPlot.jl\demo\implot_demo.jl:41
in expression starting at none:0
unsafe_load at .\pointer.jl:105 [inlined]
unsafe_load at .\pointer.jl:105 [inlined]
SineWave at C:\Users\user\code\ImPlot.jl\demo\implot_demo.jl:41
unknown function (ip: 00000000610fa005)
.text at C:\Users\user\.julia\artifacts\bc6d4eab4f69b524f9d68ed421348827a9def601\bin\libcimplot.dll (unknown line)
_ZN6ImPlot9PlotLineGEPKcPF11ImPlotPointPviES3_ii at C:\Users\user\.julia\artifacts\bc6d4eab4f69b524f9d68ed421348827a9def601\bin\libcimplot.dll (unknown line)
PlotLineG at c:\Users\user\code\ImPlot.jl\src\libcimplot.jl:1590
PlotLineG at c:\Users\user\code\ImPlot.jl\src\libcimplot.jl:1590
unknown function (ip: 00000000610fe58c)
ShowDemoWindow at C:\Users\user\code\ImPlot.jl\demo\implot_demo.jl:1193
#3 at C:\Users\user\code\ImPlot.jl\demo\implot_demo.jl:1939 [inlined]
renderloop at C:\Users\user\code\ImPlot.jl\demo\Renderer.jl:70
#4 at .\task.jl:411
unknown function (ip: 00000000610fc693)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:839
Allocations: 14985917 (Pool: 14977238; Big: 8679); GC: 20

```

**Comment by wsphillips** [comment]
Yeah, I'm hitting the same thing specifically on Windows but not on Linux. BUT it happens on `main` as well as this branch. So it's not the new code. Are you 100% sure getters were working for you in the past?

@Gnimuc it looks like we're hitting problems with the pointer load in our callback function, but only on Windows. In other parts of the demo (which also use getter functions) it's sometimes producing a `ReadOnlyMemoryError()` exception. Any advice or suggestions? Have you seen similar platform specific bugs like this before?

I recommend we file it as a separate issue and keep moving forward here.

**Comment by sairus7** [comment]
No, I'm not sure it was working in the past.
> I recommend we file it as a separate issue and keep moving forward here.

I agree

**Comment by wsphillips** [comment]
I'm going to consider this "good enough" and move on to a separate PR for upgrading to the binaries in CImGuiPack_jll

**Pull request merged**
